input to deploy image tag other than ref_name
UbiqueInnovation/workflows-backend pull request #21
Opened 2022-07-11 13:09 UTC by kistlers

2022-07-12 11:52 UTC, kistlers commented
Hab noch `config_map_prefix` added, damit das problem von heute morgen nicht nochmals so passiert

2022-07-12 12:31 UTC, ubamrein requested changes

2022-07-12 12:31 UTC, ubamrein commented on .github/workflows/k8s_deploy.yml
> +            config_map_refix:
```suggestion
            config_map_prefix:
```
Probably prefix right?

2022-08-22 09:31 UTC, ubamrein approved these changes

2022-08-22 14:03 UTC, merged