Generic docker Workflow
UbiqueInnovation/workflows-backend pull request #75
Opened 2023-08-10 15:57 UTC by SebastianThomas

2023-08-11 20:22 UTC, dsparber commented on CHANGELOG.md
> +## v2.1
```suggestion
## v3 (upcoming)
```

2023-08-11 20:22 UTC, dsparber commented on .github/workflows/generic_docker_image.yml
> +            ref_name:
Unused input variable?

2023-08-14 07:32 UTC, kistlers commented on .github/workflows/generic_docker_image.yml
> +                description: name of the tag
```suggestion
                description: name of the tag to build
```

2023-08-14 07:35 UTC, kistlers approved these changes

2023-08-14 07:35 UTC, kistlers requested changes
See comments

2023-08-14 08:50 UTC, kistlers approved these changes

2023-08-14 08:53 UTC, merged